Use www-data for deploy
This way no matter who deploys, it is always clean - and importantly, we can consistently copy node_modules and run update instead of npm install each time (which takes ages).

diff --git a/usr/local/bin/deploy b/usr/local/bin/deploy
--- a/usr/local/bin/deploy
+++ b/usr/local/bin/deploy
@@ -23,14 +23,17 @@ build() {
 
   cd $repo_dirname
 
+  echo ">>> copying node modules from v$(json -f ../jsbin/package.json version)..."
+  cp -R ../jsbin/node_modules .
+
   if [ -z "$d" ]; then
-    echo ">>> no change in packages, copying from v$(json -f ../jsbin/package.json version)..."
-    cp -R ../jsbin/node_modules .
+    echo ">>> no update required"
   else
-    echo ">>> installing fresh npm modules"
+    echo ">>> updating npm modules"
     npm install &> /dev/null
   fi
 
+  echo ">>> running build..."
   grunt build &> /dev/null
 }
 
@@ -62,7 +65,24 @@ main() {
 
   symlink_repo_to_name "$project_name-$tag" $project_name
   echo ">>> deploy complete"
-  exit 0
 }
 
-main $ARGS
+restart() {
+  echo ">>> restarting..."
+  sudo restart jsbin
+}
+
+if [ "$USER" != "www-data" ]
+then
+  echo "*** launching deploy as www-data"
+  sudo -u www-data -- sh -c "/usr/local/bin/deploy $ARGS"
+  if [ $? -ne 0 ]; then
+    echo "*** deploy failed"
+    exit 1;
+  else
+    restart
+  fi
+else
+  main $ARGS
+  echo "*** exiting from www-data"
+fi
